version: '3'
services:
  app:
    container_name: listingserver4
    restart: always
    build: .
    ports:
      - '80:3008'
    links:
      - mongo
    
    stdin_open: true
    tty: true
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
